"""empty message

Revision ID: 6cf75eba04bf
Revises: 3b5b2336299f
Create Date: 2017-10-29 14:30:37.487811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf75eba04bf'
down_revision = '3b5b2336299f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('elements', sa.Column('sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elements', 'sheets', ['sheet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elements', type_='foreignkey')
    op.drop_column('elements', 'sheet_id')
    op.drop_table('sheets')
    op.drop_table('users')
    # ### end Alembic commands ###
